# -*- coding: utf-8 -*-
"""GH_Marina_Lima_Braga - Lab-1-Text-Classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/144gWbRl8LublGIirZPSRoOD_xtmI9XKz
"""

import nltk
nltk.download('movie_reviews') # loads the dataset
nltk.download('punkt')
#!python -m spacy download "en_core_web_sm"

from nltk.corpus import movie_reviews
  import random
  import spacy
  from scipy.sparse import coo_matrix, vstack
  import matplotlib.pyplot as plt
  from sklearn.linear_model import LogisticRegression
  from sklearn.feature_extraction.text import CountVectorizer

  nlp_en = spacy.load("en_core_web_sm", disable=['ner', 'parser'])

  documents = [(movie_reviews.raw(fileid), category)
                for category in movie_reviews.categories()
                for fileid in movie_reviews.fileids(category)]

  print("number of docs loaded:", len(documents))

  corpus_raw = [ x[0] for x in documents ]  # corpus_raw is a list of strings (reviews) to be converted into vectors
  y_corpus = [ x[1] for x in documents ]    # y_corpus are the sentiment labels of the reviews (nothing to be done here)
  print(corpus_raw[0])
  print(y_corpus[0])

  random.seed(42)

import numpy as np
import nltk
from nltk.corpus import movie_reviews
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV, train_test_split, StratifiedKFold
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import spacy

# Load English NLP model
nlp_en = spacy.load("en_core_web_sm", disable=['ner', 'parser'])

# Load movie reviews dataset
documents = [(movie_reviews.raw(fileid), category)
             for category in movie_reviews.categories()
             for fileid in movie_reviews.fileids(category)]

# Extract text and labels
corpus_raw = [x[0] for x in documents]
y_corpus = np.array([1 if x[1] == "pos" else 0 for x in documents])

# Split dataset into Train (70%) and Test (30%)
X_train_val, X_test, y_train_val, y_test = train_test_split(
    corpus_raw, y_corpus, test_size=0.3, random_state=42
)

# Further split into Train (75%) and Validation (25%)
X_train, X_val, y_train, y_val = train_test_split(
    X_train_val, y_train_val, test_size=0.25, random_state=42
)

print(f"Train set: {len(X_train)}, Validation set: {len(X_val)}, Test set: {len(X_test)}")

bow_vectorizer = CountVectorizer()
X_train_bow = bow_vectorizer.fit_transform(X_train)
X_val_bow = bow_vectorizer.transform(X_val)
X_test_bow = bow_vectorizer.transform(X_test)

tfidf_vectorizer = TfidfVectorizer()
X_train_tfidf = tfidf_vectorizer.fit_transform(X_train)
X_val_tfidf = tfidf_vectorizer.transform(X_val)
X_test_tfidf = tfidf_vectorizer.transform(X_test)

def spacy_vectorize(texts, nlp_model):
    return np.array([nlp_model(text).vector for text in texts])

X_train_spacy = spacy_vectorize(X_train, nlp_en)
X_val_spacy = spacy_vectorize(X_val, nlp_en)
X_test_spacy = spacy_vectorize(X_test, nlp_en)

param_grid = {
    "C": [0.01, 0.1, 1, 10, 100],  # Regularization strength
    "max_iter": [100, 200, 500],   # Number of iterations
}

cv_strategy = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

def train_and_tune(X_train, X_val, y_train, y_val):
    log_reg = LogisticRegression(random_state=42, class_weight="balanced", solver="liblinear")

    grid_search = GridSearchCV(
        log_reg, param_grid, cv=cv_strategy, scoring="accuracy", n_jobs=-1, verbose=1
    )
    grid_search.fit(X_train, y_train)

    # Evaluate on validation set
    best_model = grid_search.best_estimator_
    y_val_pred = best_model.predict(X_val)
    val_acc = accuracy_score(y_val, y_val_pred)

    print(f"Best Hyperparameters: {grid_search.best_params_}")
    print(f"Validation Accuracy: {val_acc:.4f}")
    print("\nClassification Report:\n", classification_report(y_val, y_val_pred))

    return best_model, val_acc

# Train models for each representation
print("\nTraining BoW Model...")
best_bow_model, acc_bow = train_and_tune(X_train_bow, X_val_bow, y_train, y_val)

print("\nTraining TF-IDF Model...")
best_tfidf_model, acc_tfidf = train_and_tune(X_train_tfidf, X_val_tfidf, y_train, y_val)

print("\nTraining SpaCy Model...")
best_spacy_model, acc_spacy = train_and_tune(X_train_spacy, X_val_spacy, y_train, y_val)

# Select the best model based on validation accuracy
best_model = None
best_representation = None

if max(acc_bow, acc_tfidf, acc_spacy) == acc_bow:
    best_model = best_bow_model
    best_representation = "BoW"
    X_train_final = bow_vectorizer.fit_transform(X_train_val)
    X_test_final = bow_vectorizer.transform(X_test)
elif max(acc_bow, acc_tfidf, acc_spacy) == acc_tfidf:
    best_model = best_tfidf_model
    best_representation = "TF-IDF"
    X_train_final = tfidf_vectorizer.fit_transform(X_train_val)
    X_test_final = tfidf_vectorizer.transform(X_test)
else:
    best_model = best_spacy_model
    best_representation = "SpaCy"
    X_train_final = spacy_vectorize(X_train_val, nlp_en)
    X_test_final = spacy_vectorize(X_test, nlp_en)

print(f"\nBest Model: {best_representation}")

# Retrain best model on Train + Validation set
best_model.fit(X_train_final, y_train_val)

y_test_pred = best_model.predict(X_test_final)
test_accuracy = accuracy_score(y_test, y_test_pred)

print(f"\nTest Accuracy: {test_accuracy:.4f}")
print("\nFinal Classification Report:\n", classification_report(y_test, y_test_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_test_pred))

import pandas as pd

def print_top_tokens(model, vectorizer, top_n=30):
    # Extract feature names (tokens) and model coefficients
    feature_names = vectorizer.get_feature_names_out()
    coefs = model.coef_[0]

    # Combine tokens with their corresponding coefficients
    coef_df = pd.DataFrame({
        'token': feature_names,
        'coefficient': coefs,
        'abs_coefficient': np.abs(coefs)
    })

    # Sort by absolute value to get the most influential tokens
    top_tokens = coef_df.sort_values(by='abs_coefficient', ascending=False).head(top_n)

    print(f"\nTop {top_n} tokens by absolute coefficient weight (BoW):\n")
    print(top_tokens[['token', 'coefficient']].to_string(index=False))

# Call the function with the best BoW model
print_top_tokens(best_bow_model, bow_vectorizer)

